# Generated by Django 3.0.3 on 2020-08-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browserEngine', models.CharField(max_length=100)),
                ('browserLanguage', models.CharField(max_length=100)),
                ('browserName', models.CharField(max_length=100)),
                ('browserOnline', models.CharField(max_length=100)),
                ('browserPlatform', models.CharField(max_length=100)),
                ('browserVersion1a', models.CharField(max_length=100)),
                ('browserVersion1b', models.CharField(max_length=100)),
                ('dataCookies1', models.CharField(max_length=100)),
                ('dataCookies2', models.CharField(max_length=100)),
                ('dataCookiesEnabled', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('ipAddress1', models.CharField(max_length=100)),
                ('ipAddress2', models.CharField(max_length=100)),
                ('javaEnabled', models.CharField(max_length=100)),
                ('pageOn', models.CharField(max_length=100)),
                ('previousSites', models.CharField(max_length=100)),
                ('referrer', models.CharField(max_length=100)),
                ('screenColorDepth', models.CharField(max_length=10)),
                ('screenPixelDepth', models.CharField(max_length=10)),
                ('sizeAvailHeight', models.CharField(max_length=10)),
                ('sizeAvailWidth', models.CharField(max_length=10)),
                ('sizeDocumentHeight', models.CharField(default='', max_length=10)),
                ('sizeDocumentWidth', models.CharField(default='', max_length=10)),
                ('sizeIn', models.CharField(max_length=10)),
                ('sizeInHeight', models.CharField(max_length=10)),
                ('sizeScreenHeight', models.CharField(max_length=10)),
                ('sizeScreenWidth', models.CharField(max_length=10)),
                ('timeOpened', models.CharField(max_length=100)),
                ('timestamp', models.CharField(max_length=20)),
            ],
        ),
    ]
