# Generated by Django 3.0.3 on 2020-08-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0002_auto_20200820_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='browserEngine',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='browserLanguage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='browserName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='browserOnline',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='browserPlatform',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='browserVersion1a',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='browserVersion1b',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='dataCookies1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='dataCookies2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='dataCookiesEnabled',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='ipAddress1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='ipAddress2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='javaEnabled',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='latitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='longitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='pageOn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='previousSites',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='referrer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='screenColorDepth',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='screenPixelDepth',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='sizeAvailHeight',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='sizeAvailWidth',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='sizeDocumentHeight',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='sizeDocumentWidth',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='sizeIn',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='sizeInHeight',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='sizeScreenHeight',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='sizeScreenWidth',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='timeOpened',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='timestamp',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
